name: conversor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-35.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.2
  go_router: ^11.1.2
  intl: ^0.18.1
  number_text_input_formatter: ^1.0.0+7
  riverpod_annotation: ^2.1.6

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: 3.0.0-dev.2
  riverpod_lint: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
